### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by BlueDragon709** [lukearran/GNOME-Cast-Control#1]
I get this issue after following the auto installation guide:
SyntaxError: missing ( before catch

Stack trace:
  @/home/brian/.local/share/gnome-shell/extensions/castcontrol@hello.lukearran.com/prefs.js:11:7
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43

**Comment by lukearran** [comment]
Thanks for raising an issue,

Is this when opening the preferences window? Can you also let me know the GNOME version & Linux distribution you're using please? 

Kindest Regards

Luke

**Comment by BlueDragon709** [comment]
Sorry for the late response.
I am running: 
Ubuntu 18.04.3 LTS
GNOME 3.28.2

![image](https://user-images.githubusercontent.com/11785665/68457485-b5b4c500-0200-11ea-8d31-4717697622b1.png)
And it showed a warning sign so when i clicked on the cog i got that warning.

**Comment by lukearran** [comment]
Thanks for your response,

I've reproduced the issue. I'll get this fixed in the next few days.

Kindest Regards

Luke

**Comment by BlueDragon709** [comment]
Did you manage to fix it?

**Comment by lukearran** [comment]
No, sorry for the delay. I did take a look into the issue, but I haven't found a workable fix as of yet, and sadly I don't have the time to investigate this further until December. So please hang tight and I will make sure this gets resolved next month.

**Comment by lukearran** [comment]
Sorry that this issue was never resolved - but I just wanted to update this issue for future reference.

Going forward, I will be focusing on maintaing this extension for the current major GNOME Shell (3.36) version and the previous major version.
