### ISSUE TITLE
Cast-control sees devices; thinks nothing is playing

### ISSUE THREAD

**Issue by TheRoarkster** [lukearran/GNOME-Cast-Control#2]
I've been waiting for this extension!!!  Very exciting.  

Unfortunately, after installing manually (the GNOME shell website install results in an ERROR on Manjaro 18.1.5 and GNOME shell 3.34.3), the extension shows up in the menu bar and identifies all of my cast devices -- but it reports all with "Nothing Playing" even though one is playing.  

Happy to help troubleshoot.  

Also, would be great if the extension identified the last connected or currently playing device and put media controls in the menu bar instead of "Home."

**Comment by lukearran** [comment]
Great, glad to hear, and thanks for your suggestion! I'll make sure to look into it once I get the time to develop this extension further.

In regards to the "Nothing Playing" issue, that sounds like it's an API issue (provided by [cast-web-api-cli](https://github.com/vervallsweg/cast-web-api-cli)) - please take a look at the following endpoint  to confirm what information your devices are returning: [http://localhost:3000/device](http://localhost:3000/device)

Kindest Regards

Luke

**Comment by TheRoarkster** [comment]
Appreciate it.  Here is the information from localhost. Hopefully, it helps. 

`[{"id":"3a8448445707021583c081c14beb04cff","name":"Front Deck","connection":"connected","address":{"port":8009,"host":"10.0.5.40"},"sessionId":null,"status":{"groupPlayback":false,"volume":44,"muted":false,"application":"","status":"","title":"","subtitle":"","image":""},"groups":[],"members":[]},{"id":"731045445-264c-439b-97dc-5336516ba664","name":"Outside Only","connection":"connected","address":{"port":42700,"host":"10.0.5.40"},"sessionId":null,"status":{"groupPlayback":false,"volume":44,"muted":false,"application":"","status":"","title":"","subtitle":"","image":""},"groups":[],"members":[]},{"id":"7ba45544-e011-44c9-b0a8-a8a7555f11a5","name":"All Devices","connection":"connected","address":{"port":42470,"host":"10.0.5.40"},"sessionId":null,"status":{"groupPlayback":false,"volume":44,"muted":false,"application":"","status":"","title":"","subtitle":"","image":""},"groups":[],"members":[]}]`

**Comment by TheRoarkster** [comment]
A little progress....I manually restarted `cast-web-api-cli` via `cast-web-api-cli stop` and `cast-web-api-cli start`.  

The result was that, briefly, `Cast-Control` saw one of my devices as casting.  But it could not control the device using Play, Pause, Stop, etc.  And it reverted back to "Nothing Playing" after about 5-30 seconds.  

Also, `cast-web-api-cli` status reported address 127.0.0.1:3000, which the help page states is a fallback for error.  I manually reinstalled `cast-web-api-cli` and got the same result.  It is still falling back to the error address.  Not sure if that matters.

**Comment by lukearran** [comment]
If you're continuing to have this issue, please can you report it on ['cast-web-api-cli' GitHub repository.](https://github.com/vervallsweg/cast-web-api-cli) This appears to be an issue with the network discover within the npm module, rather than the extension.
